
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace anketproje.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Kayit
{

    public string kayitId { get; set; }

    public string kayitSoruId { get; set; }

    public string kayitUyeId { get; set; }



    public virtual Soru Soru { get; set; }

    public virtual Uye Uye { get; set; }

}

}
